from __future__ import annotations


def build(spec: dict) -> dict:
    rank = spec["rank"]
    market_rank = spec.get("market_rank", rank)
    name = spec["name"]
    ticker = spec["ticker"]
    return {
        "TITLE": f"{name}经营全解析",
        "SUBTITLE": spec["subtitle"],
        "UPDATE_DATE": spec.get("update_date", "数据更新：FY2025 年报/业绩公告 + CompaniesMarketCap，2026年6月"),
        "COMPANY_PROFILE": spec["profile"],
        "FINANCIAL_SUMMARY": spec["financial"],
        "SEGMENTS_LABEL": spec.get("segments_label", "业务分部 / 经营结构"),
        "BUSINESS_SEGMENTS": spec["segments"],
        "REVENUE_MIX": spec["mix"],
        "MOVES_LABEL": "关键战略动作",
        "STRATEGIC_MOVES": spec["moves"],
        "MOAT": spec["moat"],
        "MOAT_METRICS": spec["moat_metrics"],
        "MOAT_CONTEXT": spec.get("moat_context", {}),
        "KEY_METRICS": [
            ("市值排名", f"第 {market_rank} 名"),
            ("FY25 营收", spec["key_revenue"]),
            ("经营利润", spec["key_operating_profit"]),
            ("经营现金流", spec["key_ocf"]),
            ("净利润", spec["key_net_income"]),
            ("当前市值", spec["market_cap_short"]),
            ("PE / Forward PE", spec["pe_forward"]),
            ("核心指标", spec["core_metric"]),
            ("股东回报", spec["shareholder_return"]),
            ("股息", spec["dividend"]),
        ],
        "CAPITAL_AND_ROI": spec["capital"],
        "MAJOR_HOLDERS": spec.get("major_holders", []),
        "RISKS_HIGHLIGHTS": spec["risks"],
        "QUOTES_LABEL": "管理层 & 战略观点",
        "QUOTES": spec["quotes"],
        "DATA_SOURCE": spec["data_source"],
        "FOOTER_LINES": spec["footers"],
        "LOGO_SLUG": spec["slug"],
    }


SPECS = {
    "ccb": {
        "rank": 35,
        "slug": "ccb",
        "name": "中国建设银行",
        "ticker": "601939.SS / 0939.HK",
        "subtitle": "China Construction Bank · 国有大行 + 零售金融 + 普惠信贷",
        "profile": {
            "公司全称": "China Construction Bank Corporation",
            "上市代码": "SSE: 601939 / HKEX: 0939",
            "成立": "1954 年",
            "董事长": "张金良",
            "核心业务": "公司金融 + 个人金融 + 资金资管 + 金融科技",
            "总部": "北京",
            "当前市值": "约 $3,839 亿美元（CMC 第35名）",
            "PE / Forward PE": "约 7.6× / 7×",
        },
        "financial": {
            "FY2025 营收": "$109.4B（RMB740.9B）",
            "FY2025 经营利润": "$72B级（拨备前利润）",
            "FY2025 经营现金流": "银行现金流不可比",
            "FY2025 净利润": "$50.2B（RMB339.8B，+1.0%）",
            "当前市值": "约 $383.9B",
            "PE / Forward PE": "约 7.6× / 7×",
        },
        "segments": [
            ("1", "个人金融", "约 45%", "$49B级", "稳", "→稳定", "零售/房贷"),
            ("2", "公司金融", "约 38%", "$42B级", "稳", "→稳定", "企业信贷"),
            ("3", "资金资管", "约 12%", "$13B级", "波动", "→周期", "债券/投资"),
            ("4", "其他业务", "约 5%", "$6B级", "小", "→稳定", "综合金融"),
        ],
        "mix": [("个人金融", "45%"), ("公司金融", "38%"), ("资金资管", "12%"), ("其他", "5%")],
        "moves": [
            ("零售", "个人客户和AUM扩张", "用存款、按揭和财富管理维持低成本资金。", "#007C59"),
            ("普惠", "服务小微与制造业", "信贷投放围绕实体经济和普惠金融。", "#1E5AA8"),
            ("风控", "净息差承压", "利率下行和房地产信用仍是核心压力。", "#B8532F"),
            ("科技", "数字化银行", "手机银行和智能运营降低网点边际成本。", "#C4963C"),
        ],
        "moat": [
            ("国有大行信用", "系统重要性和国家信用背书降低资金成本。"),
            ("低成本存款", "庞大的个人和对公存款是银行最核心负债优势。"),
            ("零售客户基础", "住房金融、工资账户和财富管理形成长期客户关系。"),
            ("风控和网点规模", "大行资本、风控、网点和合规能力形成进入门槛。"),
        ],
        "moat_metrics": {
            "国有大行信用": "全球系统重要性银行",
            "低成本存款": "存款数十万亿元",
            "零售客户基础": "个人金融约45%收入",
            "风控和网点规模": "ROE约10%｜ROA约0.8%",
        },
        "capital": [
            ("ROE / ROA", "ROE约10% / ROA约0.8%", "银行不用工业 ROIC；重点看净息差、资本充足率和信用成本。"),
            ("2026E CapEx", "不适用 / 科技投入", "银行资本投入主要体现为科技系统、网点数字化和风险资产。"),
            ("股东回报", "约$0.057/股", "2025每股现金分红约RMB0.3887，折合约$0.057；含中期0.1858和末期0.2029。"),
        ],
        "risks": [
            ("亮点", "净利润约 $50B", "大型银行利润底盘深厚。"),
            ("亮点", "低成本存款", "负债成本优势仍是核心护城河。"),
            ("风险", "净息差下行", "利率周期压缩银行息差。"),
            ("风险", "地产信用", "房地产和地方融资平台风险仍需观察。"),
            ("风险", "人民币汇率", "美元展示受汇率波动影响。"),
        ],
        "quotes": ["「服务实体经济，是国有大行的长期主线。」— 年报口径"],
        "key_revenue": "$109.4B",
        "key_operating_profit": "$72B级",
        "key_ocf": "不可比",
        "key_net_income": "$50.2B",
        "market_cap_short": "$3,839亿",
        "pe_forward": "7.6× / 7×",
        "core_metric": "ROE约10%",
        "shareholder_return": "约$0.057/股",
        "dividend": "RMB0.3887/股",
        "data_source": "CCB 2025 annual results / CompaniesMarketCap / USD-CNY 6.77",
        "footers": [
            "经营数据：中国建设银行 2025 年度业绩公告，FY2025: 2025年1-12月",
            "行情数据：CompaniesMarketCap，查看：2026年6月；第35名，市值约 $383.9B",
            "ROI口径：银行采用 ROE/ROA 替代 ROIC；ROE约10%，ROA约0.8%",
            "2026 CapEx口径：银行无可比工业 CapEx；以科技系统、网点数字化和风险资产为主",
            "股东分红：中国建设银行2025年度业绩公告 / DividendMax / Morningstar，查看：2026年6月；中期RMB0.1858/股 + 末期RMB0.2029/股，合计约RMB0.3887/股（约$0.057/股）",
            "管理文化：CCB 年报/战略表述/社会责任报告，核查：2026年6月",
            "汇率口径：人民币金额按约 1 USD = 6.77 CNY 折算，查看：2026年6月",
            "免责声明：本图仅供学习参考，不构成投资建议",
            "by 江明",
        ],
    },
    "abbvie": {
        "rank": 36,
        "slug": "abbvie",
        "name": "AbbVie",
        "ticker": "ABBV",
        "subtitle": "AbbVie (NYSE: ABBV) · 免疫药物 + 神经科学 + 美学医药",
        "profile": {
            "公司全称": "AbbVie Inc.",
            "上市代码": "NYSE: ABBV",
            "成立": "2013 年自 Abbott 分拆",
            "CEO": "Robert A. Michael",
            "核心业务": "Immunology + Neuroscience + Oncology + Aesthetics",
            "总部": "North Chicago, Illinois",
            "当前市值": "约 $3,825 亿美元（CMC 第36名）",
            "PE / Forward PE": "GAAP约92× / Forward约15×",
        },
        "financial": {
            "FY2025 营收": "$61.2B（+8.6%）",
            "FY2025 经营利润": "$18B级（调整后高利润）",
            "FY2025 经营现金流": "$20B级",
            "FY2025 净利润": "$4.2B（GAAP EPS $2.36）",
            "当前市值": "约 $382.5B",
            "PE / Forward PE": "约 92× / 15×",
        },
        "segments": [
            ("1", "Immunology", "约 50%", "$30B级", "高增", "▲增长", "Skyrizi/Rinvoq"),
            ("2", "Neuroscience", "约 18%", "$11B级", "增长", "▲增长", "Botox/Vraylar"),
            ("3", "Oncology", "约 11%", "$7B级", "成熟", "→稳定", "Venclexta"),
            ("4", "Aesthetics", "约 9%", "$5B级", "承压", "→修复", "Botox/Juvederm"),
        ],
        "mix": [("免疫", "50%"), ("神经科学", "18%"), ("肿瘤", "11%"), ("美学", "9%")],
        "moves": [
            ("免疫", "Skyrizi + Rinvoq 接棒", "两款药成为后 Humira 时代核心增长引擎。", "#8B1E3F"),
            ("管线", "并购补强研发", "通过 ImmunoGen、Cerevel 等交易补齐肿瘤和神经科学。", "#4A6B3B"),
            ("专利", "Humira 下滑消化期", "老药专利悬崖仍拖累结构，但新药增速抵消。", "#B8532F"),
            ("分红", "Dividend Aristocrat", "现金流支撑持续分红和债务消化。", "#C4963C"),
        ],
        "moat": [
            ("免疫双引擎", "Skyrizi 和 Rinvoq 是 AbbVie 最关键增长资产。"),
            ("医生渠道和适应症", "免疫、神经和美学产品依赖长期医生教育和适应症扩展。"),
            ("现金流与分红纪律", "成熟药企用现金流支持研发、并购、还债和分红。"),
            ("研发并购能力", "公司擅长通过收购和内部研发补齐专利悬崖。"),
        ],
        "moat_metrics": {
            "免疫双引擎": "Skyrizi+Rinvoq高双位增",
            "医生渠道和适应症": "免疫约50%收入",
            "现金流与分红纪律": "2025股息$6.56/股",
            "研发并购能力": "调整EPS $10.00",
        },
        "capital": [
            ("ROI / ROIC", "GAAP口径受IPR&D扰动", "2025 收购研发费用压低 GAAP 净利；更适合看调整后利润率和现金流。"),
            ("2026E CapEx", "未披露精确额", "资本投入主要为研发、生产、并购整合和管线推进。"),
            ("股东回报", "$6.56/股股息", "2025季度股息为$1.64/股，全年按四次派发约$6.56/股。"),
        ],
        "risks": [
            ("亮点", "营收 $61.2B", "免疫和神经科学拉动增长。"),
            ("亮点", "新药接棒", "Skyrizi、Rinvoq 对冲 Humira 下滑。"),
            ("风险", "专利悬崖", "成熟药物面临生物类似药竞争。"),
            ("风险", "收购研发费用", "GAAP利润受 IPR&D 大幅扰动。"),
            ("风险", "药价监管", "美国医保和药价政策影响估值。"),
        ],
        "quotes": ["「进入 2026 年时，公司拥有显著动能。」— AbbVie 2025业绩口径"],
        "key_revenue": "$61.2B",
        "key_operating_profit": "$18B级",
        "key_ocf": "$20B级",
        "key_net_income": "$4.2B",
        "market_cap_short": "$3,825亿",
        "pe_forward": "92× / 15×",
        "core_metric": "调整EPS $10",
        "shareholder_return": "$6.56/股股息",
        "dividend": "$1.64/季",
        "data_source": "AbbVie FY2025 results / CompaniesMarketCap",
        "footers": [
            "经营数据：AbbVie FY2025 results / Form 10-K，FY2025: 2025年1-12月",
            "行情数据：CompaniesMarketCap，查看：2026年6月；第36名，市值约 $382.5B",
            "ROI口径：2025 GAAP 净利受 acquired IPR&D 扰动；主图用调整利润和现金流辅助判断",
            "2026 CapEx口径：公司未披露单一精确额；以研发、生产、并购整合和管线投入为主",
            "股东分红：AbbVie 2025 Form 10-Q / dividend history，查看：2026年6月；2025季度现金股息$1.64/股，全年约$6.56/股",
            "管理文化：AbbVie culture / careers / annual report，核查：2026年6月",
            "免责声明：本图仅供学习参考，不构成投资建议",
            "by 江明",
        ],
    },
    "ge": {
        "rank": 37,
        "slug": "ge",
        "name": "GE Aerospace",
        "ticker": "GE",
        "subtitle": "GE Aerospace (NYSE: GE) · 航空发动机 + 商用服务 + 军用推进",
        "profile": {
            "公司全称": "General Electric Company, operating as GE Aerospace",
            "上市代码": "NYSE: GE",
            "独立运营": "2024 年分拆后聚焦航空",
            "CEO": "H. Lawrence Culp, Jr.",
            "核心业务": "Commercial Engines & Services + Defense & Propulsion",
            "总部": "Cincinnati, Ohio",
            "当前市值": "约 $3,737 亿美元（CMC 第37名）",
            "PE / Forward PE": "约 43× / 35×",
        },
        "financial": {
            "FY2025 营收": "$45.9B（调整收入+21%）",
            "FY2025 经营利润": "$9.1B（+25%）",
            "FY2025 经营现金流": "$7.7B FCF（+24%）",
            "FY2025 净利润": "$8.7B级",
            "当前市值": "约 $373.7B",
            "PE / Forward PE": "约 43× / 35×",
        },
        "segments": [
            ("1", "Commercial Engines", "约 73%", "$33B级", "强劲", "▲增长", "LEAP/CFM"),
            ("2", "Defense & Propulsion", "约 23%", "$10B级", "稳定", "→稳定", "军用/系统"),
            ("3", "Other", "约 4%", "$2B级", "小", "→稳定", "许可/服务"),
        ],
        "mix": [("商用发动机服务", "73%"), ("军用推进", "23%"), ("其他", "4%")],
        "moves": [
            ("服务", "发动机存量变现金", "飞行小时和在役发动机推动高毛利服务。", "#005EB8"),
            ("订单", "积压约 $190B", "强需求给未来收入提供可见度。", "#C4963C"),
            ("精益", "FLIGHT DECK", "用精益体系改善交付、质量和供应链。", "#4A6B3B"),
            ("回购", "提高股东回报", "分拆后更聚焦航空现金流和回购。", "#B8532F"),
        ],
        "moat": [
            ("发动机装机基础", "商用发动机一旦装机，就带来多年维修和备件需求。"),
            ("高认证壁垒", "航空发动机安全认证周期长，新进入者很难复制。"),
            ("服务收入复利", "服务随飞行小时、机龄和发动机存量增长。"),
            ("军用推进能力", "军用航空项目周期长，客户关系和技术门槛高。"),
        ],
        "moat_metrics": {
            "发动机装机基础": "积压约$190B",
            "高认证壁垒": "航空安全认证多年",
            "服务收入复利": "商用约73%收入",
            "军用推进能力": "军用约$10B收入",
        },
        "capital": [
            ("ROI / ROIC", "FCF转化强", "分拆后更适合看经营利润、FCF和服务收入质量。"),
            ("2026E CapEx", "未披露单一额", "重点投入发动机产能、供应链、维修网络和新技术。"),
            ("股东回报", "$1.44/股+$7.6B回购", "2025普通股股息约$1.44/股；全年回购约$7.6B，现金分红总额约$1.45B。"),
        ],
        "risks": [
            ("亮点", "积压约 $190B", "订单可见度强。"),
            ("亮点", "FCF $7.7B", "现金创造能力提升。"),
            ("风险", "供应链约束", "发动机交付受供应商影响。"),
            ("风险", "事故和认证", "质量问题会影响品牌和现金流。"),
            ("风险", "估值较高", "航空景气已经被市场定价。"),
        ],
        "quotes": ["「FLIGHT DECK 正在变成持续改善的操作系统。」— GE Aerospace 年报口径"],
        "key_revenue": "$45.9B",
        "key_operating_profit": "$9.1B",
        "key_ocf": "$7.7B FCF",
        "key_net_income": "$8.7B级",
        "market_cap_short": "$3,737亿",
        "pe_forward": "43× / 35×",
        "core_metric": "积压$190B",
        "shareholder_return": "$7.6B回购",
        "dividend": "$1.44/股",
        "data_source": "GE Aerospace 2025 annual report / CompaniesMarketCap",
        "footers": [
            "经营数据：GE Aerospace 2025 Annual Report / Form 10-K，FY2025: 2025年1-12月",
            "行情数据：CompaniesMarketCap，查看：2026年6月；第37名，市值约 $373.7B",
            "ROI口径：以经营利润、FCF和服务收入质量辅助判断；传统 ROIC 需结合分拆后资产口径",
            "2026 CapEx口径：公司未披露单一精确额；重点发动机产能、供应链和维修网络",
            "股东分红：GE Aerospace 2025 10-K / Fidelity / Yahoo Finance，查看：2026年6月；2025股息约$1.44/股，回购约$7.6B，现金分红约$1.45B",
            "管理文化：GE Aerospace FLIGHT DECK / annual report / careers，核查：2026年6月",
            "免责声明：本图仅供学习参考，不构成投资建议",
            "by 江明",
        ],
    },
    "kioxia": {
        "rank": 38,
        "market_rank": 59,
        "slug": "kioxia",
        "name": "Kioxia",
        "ticker": "285A.T",
        "update_date": "数据更新：FY2025 年报/业绩公告 + CompaniesMarketCap，2026年7月",
        "subtitle": "Kioxia Holdings · NAND 闪存 + SSD + AI 存储周期",
        "profile": {
            "公司全称": "Kioxia Holdings Corporation",
            "成立时间": "2019 年 3 月 1 日",
            "总部地址": "日本东京都港区芝浦 3-1-21",
            "交易所及代码": "东京证券交易所：285A",
            "CEO / 主要负责人": "Hiroo Ota（太田裕雄）",
            "员工人数": "15,218 人（集团合并）",
            "核心业务": "NAND 闪存、SSD 及相关存储产品",
            "当前市值": "约 $2,826 亿美元（CMC 第59名）",
            "前身 / 更名": "2017年 Toshiba Memory 独立；2019年更名 Kioxia",
        },
        "financial": {
            "FY2025 营收": "$14.5B（¥2.34T）",
            "FY2025 经营利润": "$5.4B（¥870B）",
            "FY2025 经营现金流": "$1.1B（H1 ¥175B）",
            "FY2025 净利润": "$3.4B（¥554B）",
            "当前市值": "约 $282.6B",
            "PE / Forward PE": "约 82.5× / 8.6×",
        },
        "segments": [
            ("1", "SSD & Storage", "58.1%", "$8.4B级", "高增", "▲强劲", "数据中心"),
            ("2", "Flash Devices", "约 35%", "$5B级", "周期", "▲复苏", "NAND"),
            ("3", "Other", "约 7%", "$1B级", "小", "→稳定", "授权/其他"),
        ],
        "mix": [("SSD & Storage", "58.1%"), ("Flash Devices", "35%"), ("其他", "7%")],
        "moves": [
            ("AI", "企业SSD需求爆发", "生成式AI推高数据中心存储需求。", "#B0007A"),
            ("产能", "谨慎扩产", "NAND 周期波动大，资本开支必须跟随价格周期。", "#4A6B3B"),
            ("合作", "与SanDisk合资制造", "共同制造体系分担先进 NAND 投资。", "#C4963C"),
            ("财务", "利润周期反弹", "ASP 上行带来经营利润大幅恢复。", "#2E5D8A"),
        ],
        "moat": [
            ("NAND 技术栈", "从材料、晶圆、封装到控制器固件形成复杂技术链。"),
            ("AI SSD 增长", "企业级 SSD 成为生成式 AI 基础设施的一部分。"),
            ("合资制造体系", "与 SanDisk 长期合资制造分担资本投入和工艺风险。"),
            ("周期弹性", "存储价格上行时利润弹性极强，下行时则承压。"),
        ],
        "moat_metrics": {
            "NAND 技术栈": "全球NAND头部厂商",
            "AI SSD 增长": "SSD收入占58.1%",
            "合资制造体系": "SanDisk合资制造",
            "周期弹性": "经营利润¥870B",
        },
        "capital": [
            ("ROI / ROIC", "周期高位", "NAND 周期上行时 ROIC 会快速抬升，需结合价格周期判断。"),
            ("2026E CapEx", "未披露精确额", "重点为 NAND 制程、SSD、产能和设备更新；不凑单一数。"),
            ("股东回报", "$0/股普通股", "FY2025普通股未派现金股息；披露优先股分红约¥23.8B，约$0.15B。"),
        ],
        "risks": [
            ("亮点", "SSD 58.1%", "数据中心存储占比提升。"),
            ("亮点", "利润反弹", "NAND ASP 上行带来高弹性。"),
            ("风险", "周期波动", "存储价格下行会迅速压利润。"),
            ("风险", "CapEx重", "先进 NAND 投资强度大。"),
            ("风险", "汇率", "日元和美元口径差异大。"),
        ],
        "quotes": ["「AI 数据中心让存储重新成为关键基础设施。」— 产业口径"],
        "key_revenue": "$14.5B",
        "key_operating_profit": "$5.4B",
        "key_ocf": "$1.1B H1",
        "key_net_income": "$3.4B",
        "market_cap_short": "$2,826亿",
        "pe_forward": "82.5× / 8.6×",
        "core_metric": "SSD 58.1%",
        "shareholder_return": "$0/股普通股",
        "dividend": "¥0/普通股",
        "data_source": "Kioxia FY2025 filings / official company profile / CompaniesMarketCap / StockAnalysis",
        "footers": [
            "经营数据：Kioxia Integrated Report 2025 / FY2025 analysis，FY2025: 2025年4月-2026年3月",
            "公司档案：Kioxia Holdings 官方 Company Profile，核查：2026年7月；员工15,218人，截至2026年3月",
            "行情数据：CompaniesMarketCap / StockAnalysis，查看：2026年7月；第59名，市值约 $282.6B，PE约82.5× / Forward PE约8.6×",
            "ROI口径：存储周期公司 ROIC 波动大；主图用经营利润和现金流辅助判断",
            "2026 CapEx口径：公司未披露单一精确额；重点 NAND 制程、SSD、产能和设备更新",
            "股东分红：Kioxia FY2025 consolidated results / securities report，查看：2026年7月；普通股现金股息¥0/股，优先股分红约¥23.8B（约$0.15B）",
            "管理文化：Kioxia Talent Development / Diversity & Inclusion / Standards of Conduct，核查：2026年7月",
            "汇率口径：日元金额按约 1 USD = 161 JPY 折算，查看：2026年6月",
            "免责声明：本图仅供学习参考，不构成投资建议",
            "by 江明",
        ],
    },
    "unitedhealth": {
        "rank": 39,
        "market_rank": 35,
        "slug": "unitedhealth",
        "name": "UnitedHealth",
        "ticker": "UNH",
        "update_date": "数据更新：FY2025 Form 10-K + CompaniesMarketCap，2026年7月",
        "subtitle": "UnitedHealth Group · 健康保险 + Optum 医疗服务平台",
        "profile": {
            "公司全称": "UnitedHealth Group Incorporated",
            "成立时间": "1977 年 1 月",
            "总部地址": "美国明尼苏达州 Eden Prairie",
            "交易所及代码": "纽约证券交易所：UNH",
            "CEO / 主要负责人": "Stephen Hemsley",
            "员工人数": "超过 390,000 人（集团）",
            "核心业务": "UnitedHealthcare + Optum",
            "当前市值": "约 $3,897 亿美元（CMC 第35名）",
        },
        "financial": {
            "FY2025 营收": "$447.6B（+12%）",
            "FY2025 经营利润": "$19.0B（-41%）",
            "FY2025 经营现金流": "$19.7B（-19%）",
            "FY2025 净利润": "$12.1B（-16%）",
            "当前市值": "约 $389.7B",
            "PE / Forward PE": "约 32.2× / 22.5×",
        },
        "segments": [
            ("1", "UnitedHealthcare", "约 56%", "$344.9B", "+16%", "▲增长", "保险"),
            ("2", "Optum Rx", "约 25%", "$154.7B", "+16%", "▲增长", "药房福利"),
            ("3", "Optum Health", "约 16%", "$102.0B", "-3%", "▼承压", "医疗服务"),
            ("4", "Optum Insight", "约 3%", "$19.4B", "+4%", "→修复", "数据/支付"),
        ],
        "mix": [("UnitedHealthcare", "56%"), ("Optum Rx", "25%"), ("Optum Health", "16%"), ("Optum Insight", "3%")],
        "moves": [
            ("修复", "2025利润承压", "医疗成本趋势和重组费用压低盈利。", "#005DAA"),
            ("平台", "Optum 纵向整合", "把保险、药房、医生网络和数据服务连接起来。", "#2E8B57"),
            ("监管", "医保支付和反垄断", "政策审查影响估值和并购节奏。", "#B8532F"),
            ("现金", "规模现金流", "即使承压，医疗支付平台仍有强现金流。", "#C4963C"),
        ],
        "moat": [
            ("健康保险规模", "UnitedHealthcare 覆盖雇主、Medicare、Medicaid 和个人市场。"),
            ("Optum 综合平台", "医疗服务、药房和数据能力把单一保险扩展为综合医疗平台。"),
            ("药房福利网络", "Optum Rx 连接患者、雇主、药企和全国药房。"),
            ("价值医疗闭环", "价值医疗把支付方、医生和患者放进同一套结果导向体系。"),
        ],
        "moat_metrics": {
            "健康保险规模": "$447.6B集团营收｜保险榜第1",
            "Optum 综合平台": "$270.6B收入｜1.23亿人",
            "药房福利网络": "6,100万人｜6.7万家药房",
            "价值医疗闭环": "470万患者｜3年翻倍",
        },
        "moat_context": {
            "健康保险规模": "行业含义：UnitedHealthcare收入$344.9B、服务4,980万人；集团在公开上市保险公司营收榜列第1。",
            "Optum 综合平台": "行业含义：Optum收入相当于集团营收约60%，但含内部交易，不能与保险收入直接相加。",
            "药房福利网络": "行业含义：全国性药房网络形成采购、分发和数据优势；服务人数不是市场份额口径。",
            "价值医疗闭环": "行业含义：价值医疗患者较三年前翻倍，说明支付与医疗服务整合已形成真实业务规模。",
        },
        "capital": [
            ("ROE / ROI", "ROE 12.8%", "公司2026 Proxy披露FY2025 ROE为12.8%；医疗成本上行令回报低于2024。"),
            ("2026E CapEx", "$3.8B指引", "公司已在2026全年展望中公开资本开支约$3.8B，不再使用未披露占位。"),
            ("股东回报", "年化$9.28/股｜股息率约2.2%", "最新季度股息$2.32；按7月8日股价$428.19计算，前瞻年化股息率约2.17%。"),
        ],
        "major_holders": [
            ("BlackRock", "机构", "7.99%", "约$31.1B", "2026 Proxy / 2026-07-08估值", "持股72.60M股；比例来自公司Proxy，金额按$428.19/股估算。"),
            ("State Street", "机构", "4.99%", "约$19.4B", "2026Q1 13F / 2026-07-08估值", "持股45.33M股；指数与托管资金为主，不等于主动看多。"),
            ("Stephen Hemsley", "管理层", "约0.15%", "约$0.57B", "2026 Proxy / 2026-07-08估值", "董事长兼CEO持股1.336M股；属于公开披露的管理层持仓。"),
        ],
        "risks": [
            ("亮点", "营收 $447.6B", "医疗支付规模极大。"),
            ("亮点", "Optum平台", "服务和药房带来多元利润。"),
            ("风险", "医疗成本趋势", "赔付率上行压利润。"),
            ("风险", "监管调查", "医保支付和并购审查影响估值。"),
            ("风险", "信任危机", "医疗支付争议会放大舆论风险。"),
        ],
        "quotes": ["「公司预计 2026 年恢复盈利增长。」— 2025业绩口径"],
        "key_revenue": "$447.6B",
        "key_operating_profit": "$19.0B",
        "key_ocf": "$19.7B",
        "key_net_income": "$12.1B",
        "market_cap_short": "$3,897亿",
        "pe_forward": "32.2× / 22.5×",
        "core_metric": "保险营收榜第1",
        "shareholder_return": "年化$9.28/股｜2.2%",
        "dividend": "$2.32/季",
        "data_source": "UnitedHealth 2025 Form 10-K / official People & Culture / CompaniesMarketCap / StockAnalysis",
        "footers": [
            "经营数据：UnitedHealth Group FY2025 results / Form 10-K，FY2025: 2025年1-12月",
            "公司档案：UnitedHealth Group 2025 Form 10-K，核查：2026年7月；员工超过390,000人，截至2025年12月",
            "核心证据：UnitedHealth FY2025 results / Optum Rx official / UHG value-based care / CompaniesMarketCap 保险营收榜，核查：2026年7月",
            "分部口径：占比按四项披露分部收入合计计算，未扣内部交易；分部收入不可与集团营收直接相加",
            "行情数据：CompaniesMarketCap / StockAnalysis / 实时行情，查看：2026年7月；市值约 $389.7B，PE约32.2× / Forward PE约22.5×",
            "ROI口径：UnitedHealth 2026 Proxy披露FY2025 ROE 12.8%；医疗保险公司以ROE辅助替代工业ROIC",
            "2026 CapEx口径：UnitedHealth FY2025 results 之2026展望，资本开支约$3.8B，发布：2026年1月",
            "股东分红：UnitedHealth官方股息历史 / 2026年6月公告；季度$2.32，前瞻年化$9.28；按2026年7月8日股价$428.19计算股息率约2.17%",
            "机构持仓：UnitedHealth 2026 Proxy / 2026Q1 13F；金额按2026年7月8日$428.19/股估算；Vanguard因2026年3月内部重组导致集团合并口径失效，未列入当前排序",
            "管理文化：UnitedHealth Group People & Culture / EVP / Form 10-K，核查：2026年7月",
            "汇率口径：财报与行情原币均为USD，无需换算，核查：2026年7月",
            "免责声明：本图仅供学习参考，不构成投资建议",
            "by 江明",
        ],
    },
    "morganstanley": {
        "rank": 40,
        "market_rank": 40,
        "slug": "morganstanley",
        "name": "摩根士丹利",
        "ticker": "MS",
        "update_date": "数据更新：FY2025 Form 10-K + CompaniesMarketCap，2026年7月",
        "subtitle": "Morgan Stanley · 财富管理 + 投行交易 + 资产管理",
        "profile": {
            "公司全称": "Morgan Stanley",
            "成立时间": "1935 年",
            "总部地址": "美国纽约州纽约市百老汇 1585 号",
            "交易所及代码": "纽约证券交易所：MS",
            "CEO / 主要负责人": "Ted Pick",
            "员工人数": "约 83,000 人",
            "核心业务": "Institutional Securities + Wealth Management + Investment Management",
            "当前市值": "约 $3,499 亿美元（全球约第40名）",
        },
        "financial": {
            "FY2025 营收": "$70.6B（+14%）",
            "FY2025 经营利润": "$22.0B税前利润（+25%）",
            "FY2025 经营现金流": "不可比（金融机构）",
            "FY2025 净利润": "$16.9B（+26%）",
            "当前市值": "约 $349.9B",
            "PE / Forward PE": "约 20.1× / 18.0×",
        },
        "segments": [
            ("1", "Wealth Management", "约 45%", "$31.8B", "增长", "▲增长", "财富管理"),
            ("2", "Institutional Securities", "约 47%", "$33.1B", "强劲", "▲增长", "投行/交易"),
            ("3", "Investment Management", "约 9%", "$6.5B", "增长", "▲增长", "资管"),
            ("4", "Other", "约 3%", "$2B级", "小", "→稳定", "其他"),
        ],
        "mix": [("财富管理", "45%"), ("机构证券", "47%"), ("资管", "9%")],
        "moves": [
            ("财富", "客户资产 $9.3T", "财富与资管资产让收入更稳。", "#1E4E8C"),
            ("交易", "机构证券强劲", "股权和投行业务在市场活跃期弹性大。", "#4A6B3B"),
            ("平台", "E*TRADE + workplace", "用自助投资和员工股权计划获得客户入口。", "#C4963C"),
            ("资本", "ROTCE 21.6%", "高资本回报支撑分红和回购。", "#B8532F"),
        ],
        "moat": [
            ("财富管理规模", "顾问、Workplace 和 E*TRADE 共同承接个人与企业客户。"),
            ("资产获取飞轮", "Workplace 与 E*TRADE 客户持续迁移到顾问管理资产。"),
            ("机构证券网络", "投行、交易、承销和融资共享全球机构客户关系。"),
            ("投资管理平台", "Parametric、另类投资和固定收益扩充稳定管理费收入。"),
        ],
        "moat_metrics": {
            "财富管理规模": "$7.4T资产｜2,000万关系",
            "资产获取飞轮": "2025净流入>$350B｜5年>$1.6T",
            "机构证券网络": "$33.1B创纪录｜钱包份额+100bp",
            "投资管理平台": "$1.9T AUM｜Parametric $685B",
        },
        "moat_context": {
            "财富管理规模": "行业含义：庞大收费资产与客户入口降低对投行交易周期的依赖。",
            "资产获取飞轮": "行业含义：持续净流入比单年市场上涨更能证明顾问和数字渠道的客户黏性。",
            "机构证券网络": "行业含义：收入创纪录且全球客户钱包份额五年提升100bp，说明增长不只来自市场反弹。",
            "投资管理平台": "行业含义：资管规模和定制化产品补足财富管理，并形成更稳定的管理费收入。",
        },
        "capital": [
            ("ROTCE / ROE", "ROTCE 21.6%", "金融公司不用传统 ROIC；重点看 ROTCE、CET1 和客户资产增长。"),
            ("2026E CapEx", "不适用 / 技术投入", "资本投入主要体现为科技平台、顾问工具、交易系统和风险资本。"),
            ("股东回报", "前瞻$4.60/股｜股息率约2.1%", "2026三季度起季度股息拟升至$1.15；按7月8日股价$222.04计算约2.07%，另有$20B回购授权。"),
        ],
        "major_holders": [
            ("MUFG", "战略股东", "24.0%", "约$84.4B", "2026 Proxy / 2026-07-08估值", "持股380.01M股；这是长期战略持股，不是普通指数仓位。"),
            ("State Street", "机构", "7.2%", "约$25.3B", "2026 Proxy / 2026-07-08估值", "持股114.01M股；大型指数与托管机构持仓。"),
            ("Vanguard", "机构", "6.9%", "约$24.2B", "2026 Proxy / 2026-07-08估值", "持股109.04M股；被动资金占比较高，不等于主动看多。"),
            ("BlackRock", "机构", "5.7%", "约$20.1B", "2026 Proxy / 2026-07-08估值", "持股90.50M股；持股比例超过5%。"),
        ],
        "risks": [
            ("亮点", "收入 $70.6B", "2025 创纪录收入。"),
            ("亮点", "客户资产 $9.3T", "财富管理平台规模大。"),
            ("风险", "市场周期", "投行和交易受资本市场活跃度影响。"),
            ("风险", "费率压力", "财富管理收费竞争长期存在。"),
            ("风险", "监管资本", "大型金融机构受资本规则约束。"),
        ],
        "quotes": ["「Integrated Firm 是摩根士丹利长期战略主线。」— 2025业绩口径"],
        "key_revenue": "$70.6B",
        "key_operating_profit": "$22.0B税前",
        "key_ocf": "不可比",
        "key_net_income": "$16.9B",
        "market_cap_short": "$3,499亿",
        "pe_forward": "20.1× / 18.0×",
        "core_metric": "$7.4T财富资产",
        "shareholder_return": "$4.60/股｜2.1%",
        "dividend": "$1.15/季",
        "data_source": "Morgan Stanley FY2025 Form 10-K / official About & Benefits / CompaniesMarketCap / StockAnalysis",
        "footers": [
            "经营数据：Morgan Stanley FY2025 earnings release / Form 10-K，FY2025: 2025年1-12月",
            "公司档案：Morgan Stanley 2025 Form 10-K / official About，核查：2026年7月；员工约83,000人，截至2025年12月",
            "核心证据：Morgan Stanley 2026 Shareholder Letter / FY2025 Form 10-K，核查：2026年7月",
            "行情数据：CompaniesMarketCap / StockAnalysis / 实时行情，查看：2026年7月；市值约 $349.9B，PE约20.1× / Forward PE约18.0×",
            "ROI口径：金融公司采用 ROTCE 21.6% 替代 ROIC；结合 CET1 与客户资产增长判断",
            "2026 CapEx口径：金融公司无可比工业 CapEx；以科技平台、交易系统和风险资本为主",
            "股东分红：Morgan Stanley 2026年6月24日公告；拟自2026Q3起季度$1.15、前瞻年化$4.60；按2026年7月8日股价$222.04计算股息率约2.07%，另有$20B回购授权",
            "机构持仓：Morgan Stanley 2026 Proxy；比例截至2026年3月16日，金额按2026年7月8日$222.04/股估算；未发现需单列的公开知名个人大额持仓",
            "管理文化：Morgan Stanley Values / 2025 Form 10-K / Careers Benefits，核查：2026年7月",
            "汇率口径：财报与行情原币均为USD，无需换算，核查：2026年7月",
            "免责声明：本图仅供学习参考，不构成投资建议",
            "by 江明",
        ],
    },
}


DATA_BY_SLUG = {slug: build(spec) for slug, spec in SPECS.items()}
